'use client';
import {useState} from 'react';
import {ArrowUpRight,Check,LoaderCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Choice} from './Fields';import {api} from './api';
export default function Booking({onClose,services,initialService,settings}:{onClose:()=>void,services:any[],initialService:string,settings:any}){const[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState(''),[service,setService]=useState(initialService),[consent,setConsent]=useState(false),[requestId]=useState(()=>crypto.randomUUID());async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!service){setError('Please choose a service.');return;}if(!consent){setError('Please agree to be contacted about your appointment.');return;}setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));try{const r=await api('bookings',{method:'POST',body:JSON.stringify({...data,serviceId:service,consent,requestId})});setReference(r.reference);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="salon-dialog"><DialogHeader><DialogTitle className="dialog-heading">{reference?'Your moment is on its way.':'A moment, just for you.'}</DialogTitle><DialogDescription>{reference?'Your appointment request has been received.':settings.bookingNote}</DialogDescription></DialogHeader>{reference?<div className="booking-success"><span className="success-icon"><Check/></span><p>We’ll contact you to confirm your service, time and price.</p><p className="reference">Your reference: <strong>{reference}</strong></p><button className="button" onClick={onClose}>Back to the salon <ArrowUpRight size={18}/></button></div>:<form onSubmit={submit} className="form-grid"><label className="full">Your service<Choice value={service} onChange={setService} label="Your service" options={services.map(x=>({value:x.id,label:x.title}))}/></label><label>Your name<Input name="name" autoComplete="name" required minLength={2} maxLength={100}/></label><label>Phone number<Input name="phone" type="tel" autoComplete="tel" placeholder="03XX XXXXXXX" required maxLength={30}/></label><label>Preferred date<Input name="date" type="date" min={today} required/></label><label>Preferred time<Input name="time" type="time" required/></label><p className="form-hint full">Appointment times are in Pakistan Standard Time.</p><label className="full">Email (optional)<Input name="email" type="email" autoComplete="email"/></label><label className="full">Anything you’d like us to know?<Textarea name="notes" maxLength={1500} placeholder="Your event, preferred look or special requirements." rows={3}/></label><label className="honey" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="check-label full"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/>I agree to be contacted about this request and have read the privacy information.</label>{error&&<p role="alert" className="form-error full">{error}</p>}<button className="button full" disabled={busy||!settings.bookingEnabled}>{busy?<><LoaderCircle className="spin" size={18}/> Sending request…</>:<>Request appointment <ArrowUpRight size={18}/></>}</button></form>}</DialogContent></Dialog>}
